# Generated by Django 4.2.3 on 2023-07-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_name_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
